import { resolveWhatsAppMetaConfig } from "./workspaceCredentials";

export type WhatsAppBusinessProfile = { profilePictureUrl?: string; about?: string; description?: string; email?: string; address?: string; vertical?: string; websites: string[] };
export type WhatsAppBusinessProfileResult = { ok: true; profile: WhatsAppBusinessProfile } | { ok: false; reason: "NOT_CONFIGURED" | "PERMISSION_DENIED" | "API_ERROR" };
const PROFILE_FIELDS = ["about","address","description","email","profile_picture_url","websites","vertical"].join(",");
export const WHATSAPP_PROFILE_FIELD_LABELS: Array<{ key: keyof Omit<WhatsAppBusinessProfile,"websites"> | "websites"; label: string; note: string }> = [
  { key: "profilePictureUrl", label: "Profile picture", note: "Shown beside the business name in the customer's chat list." }, { key: "description", label: "Description", note: "The longer blurb on the business profile screen." }, { key: "about", label: "About", note: "The short line under the business name inside the chat." }, { key: "email", label: "Email", note: "Tappable on the business profile screen." }, { key: "websites", label: "Websites", note: "Up to two links on the business profile screen." }, { key: "address", label: "Address", note: "Optional. Only worth setting for a visitable location." }, { key: "vertical", label: "Category", note: "The industry label WhatsApp shows." },
];
function readText(value: unknown) { return typeof value === "string" && value.trim() ? value.trim() : undefined; }
export function normalizeWhatsAppBusinessProfile(raw: Record<string, unknown>): WhatsAppBusinessProfile { const websites = Array.isArray(raw.websites) ? raw.websites.filter((entry): entry is string => typeof entry === "string" && entry.trim().length > 0) : []; return { profilePictureUrl: readText(raw.profile_picture_url), about: readText(raw.about), description: readText(raw.description), email: readText(raw.email), address: readText(raw.address), vertical: readText(raw.vertical), websites }; }
export function summarizeWhatsAppBusinessProfile(profile: WhatsAppBusinessProfile) { const set: string[] = []; const missing: string[] = []; for (const field of WHATSAPP_PROFILE_FIELD_LABELS) { const populated = field.key === "websites" ? profile.websites.length > 0 : Boolean(profile[field.key]); (populated ? set : missing).push(field.label); } return { set, missing, customerVisiblePicture: Boolean(profile.profilePictureUrl), complete: missing.length === 0 }; }
type FetchOptions = { env?: Record<string,string|undefined>; workspaceId?: string | null; fetch?: typeof globalThis.fetch; revalidateSeconds?: number };
export async function fetchWhatsAppBusinessProfile(options: FetchOptions = {}): Promise<WhatsAppBusinessProfileResult> {
  const meta = await resolveWhatsAppMetaConfig({ workspaceId: options.workspaceId, env: options.env }); if (!meta) return { ok: false, reason: "NOT_CONFIGURED" };
  try { const response = await (options.fetch || globalThis.fetch)(`https://graph.facebook.com/${meta.apiVersion}/${meta.phoneNumberId}/whatsapp_business_profile?fields=${PROFILE_FIELDS}`, { headers: { Authorization: `Bearer ${meta.token}` }, ...(options.revalidateSeconds ? { next: { revalidate: options.revalidateSeconds } } : { cache: "no-store" }) } as RequestInit); if (!response.ok) { const detail = await response.text().catch(() => ""); console.error("WhatsApp business profile fetch failed", response.status, detail.slice(0,400), meta.workspaceId); if (response.status === 401 || response.status === 403) return { ok: false, reason: "PERMISSION_DENIED" }; return { ok: false, reason: "API_ERROR" }; } const payload = await response.json().catch(() => null) as { data?: unknown } | null; const rows = Array.isArray(payload?.data) ? payload!.data as Array<Record<string,unknown>> : []; return { ok: true, profile: normalizeWhatsAppBusinessProfile(rows[0] || {}) }; } catch (error) { console.error("Unable to reach Meta for the WhatsApp business profile", error); return { ok: false, reason: "API_ERROR" }; }
}
export function isWhatsAppProfilePictureUrl(value: string): boolean { try { const url = new URL(value); if (url.protocol !== "https:") return false; return url.hostname === "pps.whatsapp.net" || url.hostname.endsWith(".whatsapp.net"); } catch { return false; } }
