import Link from "next/link";
import { cookies } from "next/headers";
import { DashboardHeading } from "@/components/dashboard/DashboardShell";
import { canonicalContentAutomationAccess } from "@/lib/unifiedAuthorization";
import { readWebGrowthSessionFromCookieStore } from "@/lib/webGrowthSession";

export default async function DashboardSettingsPage() {
  const jar = await cookies();
  const session = readWebGrowthSessionFromCookieStore(jar)!;
  return <main><DashboardHeading eyebrow="Settings" title="Web Growth account settings" description="The shared session is the account boundary. Provider credentials and module permissions remain independently managed inside their respective services." /><section className="mt-8 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-white/[0.025] p-6"><h2 className="font-semibold">Account identity</h2><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-white/35">Name</dt><dd className="mt-1 text-white/75">{session.fullName || "Not provided"}</dd></div><div><dt className="text-white/35">Email</dt><dd className="mt-1 text-white/75">{session.email || "TikTok-linked identity"}</dd></div><div><dt className="text-white/35">Sign-in provider</dt><dd className="mt-1 capitalize text-white/75">{session.provider}</dd></div><div><dt className="text-white/35">TikTok scheduler</dt><dd className="mt-1 text-white/75">{session.schedulerUserId ? "Linked" : "Not linked"}</dd></div><div><dt className="text-white/35">Content Automation</dt><dd className="mt-1 text-white/75">{canonicalContentAutomationAccess(session) ? "Administrator" : "Not authorized"}</dd></div></dl></article><article className="rounded-2xl border border-white/10 bg-white/[0.025] p-6"><h2 className="font-semibold">Module settings</h2><div className="mt-5 grid gap-3"><Link href="/dashboard/connections/" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 hover:border-emerald-300/25">Social and channel connections</Link><Link href="/scheduler/settings/" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 hover:border-emerald-300/25">TikTok publishing and account controls</Link><Link href="/admin/content-automation/" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 hover:border-emerald-300/25">Content Automation settings</Link><Link href="/admin/whatsapp/settings/" className="rounded-xl border border-white/10 px-4 py-3 text-sm text-white/70 hover:border-emerald-300/25">WhatsApp workspace settings</Link></div></article></section><section className="mt-6 rounded-2xl border border-white/10 bg-white/[0.02] p-6"><h2 className="font-semibold">Session</h2><p className="mt-2 text-sm leading-6 text-white/50">Signing out ends the shared Web Growth browser session. It does not disconnect TikTok, Meta or WhatsApp provider credentials.</p><form action="/api/auth/logout/" method="post"><button className="mt-4 rounded-full border border-white/15 px-5 py-2.5 text-sm font-semibold text-white/75 hover:border-white/30">Sign out of Web Growth</button></form></section></main>;
}
